import { GearItem } from '../types';

export const dayHikeGear: GearItem[] = [
  {
    id: 'GEAR-01',
    nameKk: 'Су өткізбейтін треккингтік етіктер (Vibram табаны)',
    nameRu: 'Треккинговые ботинки с поддержкой голеностопа',
    categoryKk: 'Киім & Аяқкиім',
    categoryRu: 'Одежда и обувь',
    weightGrams: 900,
    isEssential: true,
    packed: true,
  },
  {
    id: 'GEAR-02',
    nameKk: 'Ыстық шай немесе су үшін термос (1.0 л)',
    nameRu: 'Термос с горячим чаем/водой (1.0 л)',
    categoryKk: 'Тағам & Су',
    categoryRu: 'Питание и гидратация',
    weightGrams: 1200,
    isEssential: true,
    packed: true,
  },
  {
    id: 'GEAR-03',
    nameKk: 'Треккингтік таяқтар (қатпарлы жұп)',
    nameRu: 'Треккинговые телескопические палки',
    categoryKk: 'Жабдықтар',
    categoryRu: 'Снаряжение',
    weightGrams: 480,
    isEssential: true,
    packed: false,
  },
  {
    id: 'GEAR-04',
    nameKk: 'Жел мен жаңбырдан қорғайтын мембраналық күрте',
    nameRu: 'Ветро-влагозащитная мембранная куртка',
    categoryKk: 'Киім & Аяқкиім',
    categoryRu: 'Одежда и обувь',
    weightGrams: 350,
    isEssential: true,
    packed: true,
  },
  {
    id: 'GEAR-05',
    nameKk: 'Жеке алғашқы медициналық көмек қобдишасы (Аптечка)',
    nameRu: 'Индивидуальная походная аптечка (пластыри, эластичный бинт)',
    categoryKk: 'Қауіпсіздік',
    categoryRu: 'Безопасность',
    weightGrams: 280,
    isEssential: true,
    packed: false,
  },
  {
    id: 'GEAR-06',
    nameKk: 'Күннен қорғайтын крем (SPF 50+) және көзілдірік (Cat 3)',
    nameRu: 'Солнцезащитный крем (SPF 50+) и очки с UV400',
    categoryKk: 'Қауіпсіздік',
    categoryRu: 'Безопасность',
    weightGrams: 150,
    isEssential: true,
    packed: true,
  },
  {
    id: 'GEAR-07',
    nameKk: 'Энергетикалық батончиктер мен кептірілген жемістер',
    nameRu: 'Питательный перекус (орехи, курага, протеиновые батончики)',
    categoryKk: 'Тағам & Су',
    categoryRu: 'Питание и гидратация',
    weightGrams: 300,
    isEssential: false,
    packed: false,
  },
  {
    id: 'GEAR-08',
    nameKk: 'Powerbank (10 000 mAh) және автономды GPS карта (2GIS/OsmAnd)',
    nameRu: 'Powerbank (10 000 mAh) и оффлайн-карты гор',
    categoryKk: 'Электроника',
    categoryRu: 'Электроника',
    weightGrams: 250,
    isEssential: true,
    packed: false,
  },
  {
    id: 'GEAR-09',
    nameKk: 'Қоқыс жинауға арналған био-пакет («Leave No Trace» қағидасы)',
    nameRu: 'Пакеты для мусора (принцип «Не оставляй следов»)',
    categoryKk: 'Экология',
    categoryRu: 'Экология',
    weightGrams: 40,
    isEssential: true,
    packed: true,
  },
];

export const campingGear: GearItem[] = [
  {
    id: 'CAMP-01',
    nameKk: 'Екі қабатты желге төзімді шатыр (2 адамдық)',
    nameRu: 'Двухслойная ветроустойчивая палатка (2-местная)',
    categoryKk: 'Баспана & Ұйқы',
    categoryRu: 'Лагерь и сон',
    weightGrams: 2400,
    isEssential: true,
    packed: false,
  },
  {
    id: 'CAMP-02',
    nameKk: 'Жылы ұйықтайтын қап (Comfort -2°C)',
    nameRu: 'Спальный мешок (t комфорта -2°C)',
    categoryKk: 'Баспана & Ұйқы',
    categoryRu: 'Лагерь и сон',
    weightGrams: 1300,
    isEssential: true,
    packed: false,
  },
  {
    id: 'CAMP-03',
    nameKk: 'Жылу өткізбейтін төсеніш (Каремат R-value > 3.0)',
    nameRu: 'Теплоизолирующий коврик (каремат / самонадувайка)',
    categoryKk: 'Баспана & Ұйқы',
    categoryRu: 'Лагерь и сон',
    weightGrams: 450,
    isEssential: true,
    packed: false,
  },
  {
    id: 'CAMP-04',
    nameKk: 'Газ жанарғысы және титан қазандық жинағы',
    nameRu: 'Газовая горелка, баллон и котелок с крышкой',
    categoryKk: 'Ас дайындау',
    categoryRu: 'Кухня',
    weightGrams: 620,
    isEssential: true,
    packed: false,
  },
  {
    id: 'CAMP-05',
    nameKk: 'Маңдайшалы жарық шамы (Headlamp 300+ люмен)',
    nameRu: 'Налобный фонарь с красным и белым светом',
    categoryKk: 'Жабдықтар',
    categoryRu: 'Снаряжение',
    weightGrams: 90,
    isEssential: true,
    packed: true,
  },
  {
    id: 'CAMP-06',
    nameKk: 'Су тазалайтын ықшам сүзгі (Sawyer / Katadyn)',
    nameRu: 'Походный мембранный фильтр для воды из горных ручьев',
    categoryKk: 'Тағам & Су',
    categoryRu: 'Питание и гидратация',
    weightGrams: 85,
    isEssential: true,
    packed: false,
  },
];
