import { Room } from '../types';

export const initialRooms: Room[] = [
  // FLOOR 1
  {
    id: 'room-101',
    number: '101',
    nameKk: 'Бастауыш сынып кабинеті',
    nameRu: 'Кабинет начальных классов',
    floor: 1,
    wing: 'west',
    type: 'classroom',
    capacity: 28,
    currentStatus: 'occupied',
    teacherInCharge: 'Аманжолова Гүлнәр Ерболқызы',
    teacherRoleKk: 'Бастауыш сынып мұғалімі, педагог-шебер',
    teacherRoleRu: 'Учитель начальных классов, педагог-мастер',
    equipment: ['Интерактивті тақта SMART 75"', 'Құжат-камера', '28 оқушы планшеті'],
    coordinates: { x: -6, y: 0.5, z: -3 },
    descriptionKk: 'Заманауи эргономикалық парталармен жабдықталған кең бөлме.',
    descriptionRu: 'Просторный кабинет с эргономичной мебелью и интерактивной доской.'
  },
  {
    id: 'room-104',
    number: '104',
    nameKk: 'Медпункт және жедел медициналық көмек',
    nameRu: 'Медпункт и кабинет первой помощи',
    floor: 1,
    wing: 'center',
    type: 'medical',
    capacity: 6,
    currentStatus: 'available',
    teacherInCharge: 'Серікбаев Бақытжан Нұрланұлы',
    teacherRoleKk: 'Мектеп дәрігері, педиатр',
    teacherRoleRu: 'Школьный врач-педиатр высшей категории',
    equipment: ['Кардиограф', 'Дәрі-дәрмек аптечкасы', 'Оттегі концентраторы', 'Ростомер/Весы'],
    coordinates: { x: 0, y: 0.5, z: -4 },
    descriptionKk: 'Алғашқы медициналық тексеріс пен емдеуге арналған толық жасақталған орын.',
    descriptionRu: 'Оснащен всем необходимым для оказания неотложной медицинской помощи.'
  },
  {
    id: 'room-110',
    number: '110',
    nameKk: 'Асхана және оқушылар коворкингі',
    nameRu: 'Школьная столовая и коворкинг',
    floor: 1,
    wing: 'east',
    type: 'canteen',
    capacity: 180,
    currentStatus: 'available',
    teacherInCharge: 'Мектеп тамақтандыру қызметі',
    teacherRoleKk: 'Санитарлық бақылау маманы',
    teacherRoleRu: 'Специалист санитарного контроля',
    equipment: ['Тағам үлестіру желісі', 'Безконтактілі төлем терминалы', 'Эко-сүзгілі су станциясы'],
    coordinates: { x: 6, y: 0.5, z: -3 },
    descriptionKk: 'Дәмді, пайдалы ыстық тамақтар мен үзілістегі демалыс аймағы.',
    descriptionRu: 'Просторная обеденная зона со здоровым меню и питьевыми станциями.'
  },
  {
    id: 'room-115',
    number: '115',
    nameKk: 'Үлкен спорт кешені & Гимнастика залы',
    nameRu: 'Большой спортивный комплекс',
    floor: 1,
    wing: 'west',
    type: 'sports',
    capacity: 60,
    currentStatus: 'occupied',
    teacherInCharge: 'Рахметов Дәулет Серікұлы',
    teacherRoleKk: 'Дене шынықтыру пәні жетекшісі',
    teacherRoleRu: 'Руководитель кафедры физической культуры',
    equipment: ['Баскетбол қалқандары', 'Волейбол торы', 'Швед қабырғасы', 'Тренажерлер'],
    coordinates: { x: -6, y: 0.5, z: 3 },
    descriptionKk: 'Олимпиадалық стандарттағы жабындысы бар көпсалалы спорттық арена.',
    descriptionRu: 'Универсальный спортивный зал с безопасным амортизирующим покрытием.'
  },

  // FLOOR 2
  {
    id: 'room-201',
    number: '201',
    nameKk: 'Әкімшілік және Директор қабылдауы',
    nameRu: 'Администрация и приемная директора',
    floor: 2,
    wing: 'center',
    type: 'admin',
    capacity: 20,
    currentStatus: 'occupied',
    teacherInCharge: 'Қасымов Айдар Төлегенұлы',
    teacherRoleKk: 'Лицей директоры, PhD',
    teacherRoleRu: 'Директор лицея, доктор философии (PhD)',
    equipment: ['Бейнеконференция жүйесі Cisco', 'Құжат айналымы принтері', 'Аудио жүйе'],
    coordinates: { x: 0, y: 2.2, z: -4 },
    descriptionKk: 'Ата-аналар мен оқушыларды ресми қабылдау және мектеп басқармасы.',
    descriptionRu: 'Приемная для встреч с родителями, педагогами и официальными делегациями.'
  },
  {
    id: 'room-205',
    number: '205',
    nameKk: 'Информатика және Жасанды Интеллект зертханасы',
    nameRu: 'Лаборатория ИИ и прикладного программирования',
    floor: 2,
    wing: 'west',
    type: 'lab',
    capacity: 32,
    currentStatus: 'available',
    teacherInCharge: 'Ибраев Самат Нұрбекұлы',
    teacherRoleKk: 'Информатика оқытушысы, ACM ICPC жаттықтырушысы',
    teacherRoleRu: 'Преподаватель Computer Science, тренер олимпиадной команды',
    equipment: ['32x iMac 24" Apple Silicon', 'NVIDIA AI Edge станциясы', 'VR гарнитуралар Meta Quest 3'],
    coordinates: { x: -6, y: 2.2, z: -3 },
    descriptionKk: 'Python, веб-әзірлеу, алгоритмдер мен нейрожелілерді оқытатын заманауи хаб.',
    descriptionRu: 'Высокопроизводительный класс для обучения программированию и машинному обучению.'
  },
  {
    id: 'room-208',
    number: '208',
    nameKk: 'Физика зертханасы & STEM Hub',
    nameRu: 'Лаборатория физики и STEM Hub',
    floor: 2,
    wing: 'west',
    type: 'lab',
    capacity: 30,
    currentStatus: 'reserved',
    teacherInCharge: 'Тұрсынов Берік Сұлтанұлы',
    teacherRoleKk: 'Физика пәнінің сарапшы ұстазы',
    teacherRoleRu: 'Эксперт-учитель физики, призер республиканских конкурсов',
    equipment: ['Цифрлық датчиктер Vernier', 'Оптикалық стендтер', 'Электромагниттік құрылғылар'],
    coordinates: { x: -6, y: 2.2, z: 3 },
    descriptionKk: 'Практикалық эксперименттер мен ғылыми жобаларды дайындайтын ғылыми орталық.',
    descriptionRu: 'Лаборатория практических физических экспериментов с цифровыми датчиками.'
  },
  {
    id: 'room-214',
    number: '214',
    nameKk: 'Химия және Биология ғылыми зертханасы',
    nameRu: 'Научная лаборатория химии и биологии',
    floor: 2,
    wing: 'east',
    type: 'lab',
    capacity: 26,
    currentStatus: 'cleaning',
    teacherInCharge: 'Әбдірахманова Динара Қайратқызы',
    teacherRoleKk: 'Биохимия кафедрасының жетекшісі',
    teacherRoleRu: 'Заведующая кафедрой естественных наук',
    equipment: ['Электронды микроскоптар Levenhuk', 'Сорғыш шкаф', 'Центрифуга', 'Реактивтер қоймасы'],
    coordinates: { x: 6, y: 2.2, z: -3 },
    descriptionKk: 'Биоқауіпсіздік ережелеріне сай жабдықталған соңғы үлгідегі лаборатория.',
    descriptionRu: 'Современный лабораторный комплекс со строгим соблюдением техники безопасности.'
  },
  {
    id: 'room-218',
    number: '218',
    nameKk: 'Қазақ тілі мен әдебиеті аудиториясы',
    nameRu: 'Кабинет казахского языка и литературы',
    floor: 2,
    wing: 'center',
    type: 'classroom',
    capacity: 28,
    currentStatus: 'available',
    teacherInCharge: 'Оразалиева Шолпан Мұратқызы',
    teacherRoleKk: 'Қазақ филологиясы магистрі',
    teacherRoleRu: 'Магистр филологии, педагог-исследователь',
    equipment: ['Интерактивті тақта', 'Ұлттық этно-экспозиция', 'Аудиовизуалды кітапхана'],
    coordinates: { x: 0, y: 2.2, z: 3 },
    descriptionKk: 'Абай, Шәкәрім және қазақ классиктерінің мұрасын зерттеуге арналған кеңістік.',
    descriptionRu: 'Интерактивный кабинет с богатым мультимедийным фондом национальной литературы.'
  },
  {
    id: 'room-222',
    number: '222',
    nameKk: 'Ағылшын тілі және IELTS дайындық орталығы',
    nameRu: 'Центр английского языка и подготовки к IELTS',
    floor: 2,
    wing: 'east',
    type: 'classroom',
    capacity: 24,
    currentStatus: 'occupied',
    teacherInCharge: 'Смит Сара Элизабет / Смағұлов Ерлан',
    teacherRoleKk: 'IELTS 8.5 сертификатталған оқытушы',
    teacherRoleRu: 'Сертифицированный тренер IELTS Academic (Band 8.5)',
    equipment: ['Лингафондық гарнитуралар Sony', 'Mock IELTS тест жүйесі', 'Акустикалық панельдер'],
    coordinates: { x: 6, y: 2.2, z: 3 },
    descriptionKk: 'Халықаралық емтихандарға және сөйлеу мәдениетін шыңдауға арналған арнайы бөлме.',
    descriptionRu: 'Специализированная площадка для языковой практики и сдачи пробных тестов.'
  },

  // FLOOR 3
  {
    id: 'room-301',
    number: '301',
    nameKk: 'Робототехника & Дрондар полигоны',
    nameRu: 'Центр робототехники и полигон дронов',
    floor: 3,
    wing: 'west',
    type: 'robotics',
    capacity: 24,
    currentStatus: 'available',
    teacherInCharge: 'Жұмағалиев Әлішер Маратұлы',
    teacherRoleKk: 'WRO халықаралық робототехника жаттықтырушысы',
    teacherRoleRu: 'Главный тренер сборной школы по робототехнике WRO',
    equipment: ['12x Lego Mindstorms / SPIKE Prime', '4x 3D принтер Bambu Lab X1C', 'Лазерлік станок', 'FPV дрондар'],
    coordinates: { x: -6, y: 4.0, z: -3 },
    descriptionKk: 'Инженерлік идеяларды нақты прототипке айналдыратын креативті шеберхана.',
    descriptionRu: 'Мастерская быстрого прототипирования с ЧПУ станками и 3D-печатью.'
  },
  {
    id: 'room-305',
    number: '305',
    nameKk: 'Жоғары математика және Олимпиадалық орталық',
    nameRu: 'Центр высшей математики и олимпиадной подготовки',
    floor: 3,
    wing: 'west',
    type: 'classroom',
    capacity: 26,
    currentStatus: 'occupied',
    teacherInCharge: 'Қайырбеков Нұржан Бақытұлы',
    teacherRoleKk: 'Математикадан олимпиадалық резерв бапкері',
    teacherRoleRu: 'Тренер олимпийского резерва по высшей математике',
    equipment: ['Көпфункционалды маркерлік қабырға', 'Сенсорлы проектор', 'Математикалық кітапхана'],
    coordinates: { x: -6, y: 4.0, z: 3 },
    descriptionKk: 'Күрделі есептерді шешуге және халықаралық жарыстарға дайындалуға арналған.',
    descriptionRu: 'Пространство интенсивной математической подготовки к олимпиадам IMO и Жаутыковской.'
  },
  {
    id: 'room-310',
    number: '310',
    nameKk: 'IT Support & Серверлік басқару бөлмесі',
    nameRu: 'Служба IT-поддержки и Серверная инфраструктура',
    floor: 3,
    wing: 'center',
    type: 'admin',
    capacity: 10,
    currentStatus: 'available',
    teacherInCharge: 'Әлімжанов Руслан Еркінұлы',
    teacherRoleKk: 'Жүйелік бас әкімші (Lead Sysadmin)',
    teacherRoleRu: 'Ведущий системный инженер школьной сети',
    equipment: ['10G Оптикалық коммутаторлар', 'Wi-Fi 6 бақылау жүйесі', 'Резервтік серверлер'],
    coordinates: { x: 0, y: 4.0, z: -4 },
    descriptionKk: 'Мектептің барлық желілік инфрақұрылымы мен цифрлық қызметтері басқарылатын орталық.',
    descriptionRu: 'Ядро цифровой экосистемы: мониторинг серверов, Wi-Fi 6 и хранилищ данных.'
  },
  {
    id: 'room-315',
    number: '315',
    nameKk: 'Цифрлық Кітапхана & Заманауи медиатека',
    nameRu: 'Цифровая библиотека и медиатека',
    floor: 3,
    wing: 'east',
    type: 'library',
    capacity: 70,
    currentStatus: 'available',
    teacherInCharge: 'Нұрғалиева Жанар Кенжебекқызы',
    teacherRoleKk: 'Бас кітапханашы, медиа-маман',
    teacherRoleRu: 'Заведующая медиатекой, координатор чтения',
    equipment: ['Электронды оқулықтар Kindle', 'Тыныш оқу капсулалары', 'Онлайн репозиторий'],
    coordinates: { x: 6, y: 4.0, z: -3 },
    descriptionKk: 'Мыңдаған ғылыми әдебиеттер, электронды кітаптар мен тыныш жұмыс орындары.',
    descriptionRu: 'Тихая зона для самостоятельных исследований с доступом к мировым базам данных.'
  },
  {
    id: 'room-320',
    number: '320',
    nameKk: 'Мектептің Акт залы (Assembly Hall)',
    nameRu: 'Актовый зал школы и Сцена',
    floor: 3,
    wing: 'east',
    type: 'admin',
    capacity: 250,
    currentStatus: 'available',
    teacherInCharge: 'Мектеп мәдениет ұжымы',
    teacherRoleKk: 'Іс-шаралар ұйымдастырушысы',
    teacherRoleRu: 'Координатор школьных культурных программ',
    equipment: ['LED экран 6x4м', 'Концерттік акустика JBL', 'Сахналық жарық жүйесі'],
    coordinates: { x: 6, y: 4.0, z: 3 },
    descriptionKk: 'Салтанатты жиындар, TEDxSchool конференциялары мен театрлық қойылымдар алаңы.',
    descriptionRu: 'Концертный зал для школьных конференций, дебатов и праздничных мероприятий.'
  }
];
